x="my, name is, vishnu"
print(len(x))
print("is" in x)
print("to" in x)
print("is" not in x)
print("to" not in x)
print(x[1])
print(x[12])
print(x[12:15])
print(x[12:])
print(x[:16])
print(x[-5])
print(x[-5:-12])
print(x[:-10])
print(x[-6:])
print(x.upper())
print(x.lower())
print(x.strip())
print(x.replace("vishnu","rahul"))
print(x.split(","))
a="i am from irinjalakuda"
print(x+ a)
print(f"{x} {a}")
t=21
print(f"i am {t}")
print(x.count("e"))
